apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-tenant-operator-config
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: dev/tenant-operator-config
    repoURL: 'git@github.com:ayeshasiddiqa161/test-repo-infra.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: root-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
