apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: gabbar
spec:
  quota: gabbar-large
  owners:
    users:
     - abc@gmail.com
  argocd:
      sourceRepos:
      - 'git@github.com:ayeshasiddiqa161/test-repo-infra.git'
      - 'git@github.com:ayeshasiddiqa161/test-apps-gitops.git'
      - 'https://stakater.github.io/stakater-charts'
#   templateInstances:
#   - spec:
#       template: tenant-vault-access
#       sync: true
  namespaces:
  - build
  - dev
  - prod
#   sandboxConfig:
#     enabled: true
#     private: true
  specificMetadata:
  - namespaces:
      - gabbar-build
    annotations:
      openshift.io/node-selector: node-role.kubernetes.io/pipeline=
